spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        - id: service-1
          uri: lb://service-1
          predicates:
            - Path=/sasi/service1/**
        - id: service-2
          uri: lb://service-2
          predicates:
            - Path=/sasi/service2/**